seed: 0

wandb:
  enabled: false
  project: crowd-reaction-analysis
  entity: null
  tags: []
  notes: null
  mode: online

data:
  audios_info_csv: /gpfs/scratch/acw723/data/audios_info.csv
  weak_labels_csv: /gpfs/scratch/acw723/data/weak_labelling/_weak_labels.csv
  strong_labels_dir: /gpfs/scratch/acw723/data/strong_labelling
  original_audio_dir: /gpfs/scratch/acw723/data/original_audio_files
  sample_rate: 16000
  chunk_sec: 20.0
  instance_sec: 1.0
  num_classes: 2

model:
  beats_checkpoint_path: /data/home/acw723/crowd_reaction_analysis/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt
  num_classes: 2
  head_hidden_dim: 256
  head_dropout: 0.1

optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-4

loss:
  class_weights: [1.0, 1.0]

trainer:
  epochs: 25

train:
  batch_size: 4
  num_workers: 0

val:
  batch_size: 4
  num_workers: 0
  threshold: 0.5
  event_collar_sec: 1.0
  event_offset_ratio: 0.2
